typography_spectrum: 1
color:
  brandColors:
    - '#f0f5f8'
    - '#000000'
    - '#a4adb6'
    - '#20232a'
    - '#464b51'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.50572
analytics:
  google: null
  facebook: null
  twitter: null
name: ' a bike blog'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Four hundred castles
description: A bike travel through time
purpose: []
