name: Flowers for Algernon
favicon: null
layout_spectrum: 0.6721154639963061
typography_spectrum: 0.38075657514855266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6789994600694627
  lightness: 0.20995697611942887
  saturation: 0.5267162807285786
  rhythmicContrast: 0.500284208683297
purpose: []
