name: ' traveling through time'
favicon: null
layout_spectrum: 0.50572
typography_spectrum: 1
title: Four hundred castles
description: 20 bike trips in the Canton of Zürich
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f5f8'
    - '#000000'
    - '#a4adb6'
    - '#20232a'
    - '#464b51'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
